#!/usr/bin/env bash

# Honeypot Client Installation Script
# This script installs and configures the honeypot client

set -euo pipefail

INSTALL_DIR="/opt/honeypot"
HONEYPOT_USER="honeypot"
PORT_OFFSET_DEFAULT=10000

SERVER_URL=""
HONEYPOT_ID=""
# Native service ports are the default. The dashboard adds --no-map-ports when
# an operator explicitly chooses backup ports for a deployment.
MAP_PORTS="yes"
PORT_OFFSET="$PORT_OFFSET_DEFAULT"
PORT_MAPPING_MANAGED_BY_SYSTEMD="no"

usage() {
	cat <<'USAGE'
Usage: install.sh --server-url <url> --honeypot-id <id> [options]

Options:
  --server-url <url>     Base URL of the FlaskAuthSystem server
  --honeypot-id <id>     Honeypot ID generated by the UI
  --map-ports            Use native service ports via iptables redirects (default)
  --no-map-ports         Use backup high ports directly; do not create redirects
  --port-offset <n>      Offset for non-root ports (default: 10000)
  -h, --help             Show this help message
USAGE
}

require_root() {
	if [[ "${EUID}" -ne 0 ]]; then
		echo "This script must be run as root." >&2
		exit 1
	fi
}

parse_args() {
	while [[ $# -gt 0 ]]; do
		case "$1" in
			--server-url)
				SERVER_URL="${2:-}"
				shift 2
				;;
			--honeypot-id)
				HONEYPOT_ID="${2:-}"
				shift 2
				;;
			--map-ports)
				MAP_PORTS="yes"
				shift 1
				;;
			--no-map-ports)
				MAP_PORTS="no"
				shift 1
				;;
			--port-offset)
				PORT_OFFSET="${2:-}"
				shift 2
				;;
			-h|--help)
				usage
				exit 0
				;;
			*)
				echo "Unknown option: $1" >&2
				usage
				exit 1
				;;
		esac
	done
}

validate_args() {
	if [[ -z "$SERVER_URL" || -z "$HONEYPOT_ID" ]]; then
		echo "Missing required arguments." >&2
		usage
		exit 1
	fi
	if ! [[ "$PORT_OFFSET" =~ ^[0-9]+$ ]]; then
		echo "--port-offset must be a number." >&2
		exit 1
	fi
}

install_dependencies() {
	apt-get update -y
	apt-get install -y python3 iptables cron wget curl

	# Ensure python3-pip is installed for python3 -m pip
	command -v pip3 >/dev/null 2>&1 || apt-get install -y python3-pip
}

ensure_user_and_dirs() {
	if ! id -u "$HONEYPOT_USER" >/dev/null 2>&1; then
		useradd --system --create-home --home-dir "$INSTALL_DIR" --shell /usr/sbin/nologin "$HONEYPOT_USER"
	fi
	mkdir -p "$INSTALL_DIR"
	mkdir -p "$INSTALL_DIR/logs"
	chown -R "$HONEYPOT_USER":"$HONEYPOT_USER" "$INSTALL_DIR"
	chmod 750 "$INSTALL_DIR"
}

install_python_packages() {
	# Skip pip upgrade to avoid conflicts
	
	# Check if pip supports --break-system-packages flag (pip >= 22.1)
	local pip_flags=""
	if python3 -m pip install --help 2>/dev/null | grep -q -- '--break-system-packages'; then
		pip_flags="--break-system-packages"
	fi
	
	# Install packages using --ignore-installed to avoid conflicts with system packages
	echo "Installing Python packages..."
	
	# Install each package separately with better error handling
	for package in "honeypots" "python-socketio" "websocket-client" "twisted"; do
		echo "Installing $package..."
		if ! python3 -m pip install $pip_flags --no-warn-script-location "$package"; then
			echo "Failed to install $package. Retrying with --ignore-installed..."
			python3 -m pip install $pip_flags --ignore-installed --no-warn-script-location "$package"
		fi
	done
	
	# Verify critical package installed
	if ! python3 -c "import honeypots" 2>/dev/null; then
		echo "ERROR: honeypots package failed to install properly." >&2
		exit 1
	fi
}

download_client_files() {
	local base_url="${SERVER_URL%/}"
	local client_url="$base_url/honeypot/honeypot_client.py"

	if command -v wget >/dev/null 2>&1; then
		wget -q -O "$INSTALL_DIR/honeypot_client.py" "$client_url"
	elif command -v curl >/dev/null 2>&1; then
		curl -fsSL "$client_url" -o "$INSTALL_DIR/honeypot_client.py"
	else
		echo "Neither wget nor curl is available to download honeypot_client.py." >&2
		exit 1
	fi

	if [[ ! -s "$INSTALL_DIR/honeypot_client.py" ]]; then
		echo "Failed to download honeypot_client.py from $client_url" >&2
		exit 1
	fi

	chown "$HONEYPOT_USER":"$HONEYPOT_USER" "$INSTALL_DIR/honeypot_client.py"
	chmod 644 "$INSTALL_DIR/honeypot_client.py"
}

fix_honeypots_compat() {
	local helper_path
	helper_path=$(python3 - <<'PY'
import importlib.util

spec = importlib.util.find_spec("honeypots.helper")
if spec and spec.origin:
	print(spec.origin)
PY
)
	if [[ -z "$helper_path" ]]; then
		return
	fi
	if grep -q "from collections import Mapping" "$helper_path"; then
		sed -i 's/from collections import Mapping/from collections.abc import Mapping/' "$helper_path"
	fi
}

write_port_map_script() {
	cat <<'SH' > "$INSTALL_DIR/port-map.sh"
#!/usr/bin/env bash
set -euo pipefail

PORT_OFFSET="__PORT_OFFSET__"
ACTION="${1:-apply}"

PORTS=(
	22 23 80 443 21 25 110 143 389 3306 5432 1433 1521 6379 11211 445 161
	123 6667 3389 5900 1080 8080 8443 53 67 9200 631 9100 5060
)

add_rule() {
	local chain="$1"
	local proto="$2"
	local from_port="$3"
	local to_port="$4"
	shift 4

	if iptables -t nat -C "$chain" -p "$proto" "$@" --dport "$from_port" -j REDIRECT --to-ports "$to_port" >/dev/null 2>&1; then
		return
	fi
	iptables -t nat -A "$chain" -p "$proto" "$@" --dport "$from_port" -j REDIRECT --to-ports "$to_port"
}

remove_rule() {
	local chain="$1"
	local proto="$2"
	local from_port="$3"
	local to_port="$4"
	shift 4

	while iptables -t nat -C "$chain" -p "$proto" "$@" --dport "$from_port" -j REDIRECT --to-ports "$to_port" >/dev/null 2>&1; do
		iptables -t nat -D "$chain" -p "$proto" "$@" --dport "$from_port" -j REDIRECT --to-ports "$to_port"
	done
}

for port in "${PORTS[@]}"; do
	mapped=$((port + PORT_OFFSET))
	if [[ "$mapped" -gt 65535 ]]; then
		echo "Mapped port out of range: $port -> $mapped" >&2
		exit 1
	fi
	for proto in tcp udp; do
		case "$ACTION" in
			apply)
				add_rule PREROUTING "$proto" "$port" "$mapped"
				add_rule OUTPUT "$proto" "$port" "$mapped" -m addrtype --dst-type LOCAL
				;;
			remove)
				remove_rule PREROUTING "$proto" "$port" "$mapped"
				remove_rule OUTPUT "$proto" "$port" "$mapped" -m addrtype --dst-type LOCAL
				;;
			*)
				echo "Usage: $0 [apply|remove]" >&2
				exit 1
				;;
		esac
	done
done
SH
	sed -i "s/__PORT_OFFSET__/${PORT_OFFSET}/" "$INSTALL_DIR/port-map.sh"
	chmod 700 "$INSTALL_DIR/port-map.sh"
	chown root:root "$INSTALL_DIR/port-map.sh"
}

setup_port_mapping_service() {
	if ! command -v systemctl >/dev/null 2>&1 || ! systemctl list-unit-files >/dev/null 2>&1; then
		return 1
	fi

	cat <<EOF > /etc/systemd/system/honeypot-port-map.service
[Unit]
Description=Honeypot native-port redirects
After=network-online.target
Wants=network-online.target
Before=honeypot-client.service

[Service]
Type=oneshot
ExecStart=$INSTALL_DIR/port-map.sh apply
ExecStop=$INSTALL_DIR/port-map.sh remove
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

	systemctl daemon-reload
	if ! systemctl enable --now honeypot-port-map.service; then
		return 1
	fi
	PORT_MAPPING_MANAGED_BY_SYSTEMD="yes"
}

setup_port_mapping_cron() {
	"$INSTALL_DIR/port-map.sh" apply
	cat <<EOF > /etc/cron.d/honeypot-port-map
@reboot root $INSTALL_DIR/port-map.sh apply
EOF
	chmod 644 /etc/cron.d/honeypot-port-map
}

disable_port_mapping() {
	if [[ -f /etc/systemd/system/honeypot-port-map.service ]] && command -v systemctl >/dev/null 2>&1; then
		systemctl disable --now honeypot-port-map.service || true
		rm -f /etc/systemd/system/honeypot-port-map.service
		systemctl daemon-reload
	fi

	if [[ -x "$INSTALL_DIR/port-map.sh" ]]; then
		"$INSTALL_DIR/port-map.sh" remove
	fi
	rm -f /etc/cron.d/honeypot-port-map
}

write_config() {
	SERVER_URL="$SERVER_URL" HONEYPOT_ID="$HONEYPOT_ID" PORT_OFFSET="$PORT_OFFSET" INSTALL_DIR="$INSTALL_DIR" \
		python3 - <<'PY'
import json
import os

server_url = os.environ["SERVER_URL"].rstrip("/")
honeypot_id = os.environ["HONEYPOT_ID"]
offset = int(os.environ.get("PORT_OFFSET", "10000"))
install_dir = os.environ["INSTALL_DIR"]

protocols = {
	"ssh": 22,
	"telnet": 23,
	"http": 80,
	"https": 443,
	"ftp": 21,
	"smtp": 25,
	"pop3": 110,
	"imap": 143,
	"ldap": 389,
	"mysql": 3306,
	"postgres": 5432,
	"mssql": 1433,
	"oracle": 1521,
	"redis": 6379,
	"memcache": 11211,
	"smb": 445,
	"snmp": 161,
	"ntp": 123,
	"irc": 6667,
	"rdp": 3389,
	"vnc": 5900,
	"socks5": 1080,
	"http_proxy": 8080,
	"https_proxy": 8443,
	"dns": 53,
	"dhcp": 67,
	"elastic": 9200,
	"ipp": 631,
	"pjl": 9100,
	"sip": 5060,
}

protocol_settings = {}
for name, port in protocols.items():
	mapped = port + offset
	if mapped > 65535:
		raise SystemExit(f"Port offset too large for {name}: {mapped}")
	protocol_settings[name] = {"port": mapped}

config = {
	"server_url": server_url,
	"honeypot_id": honeypot_id,
	"protocols": sorted(protocols.keys()),
	"auto_start": False,
	"heartbeat_interval": 30,
	"log_poll_interval": 2,
	"log_dir": "logs",
	"protocol_settings": protocol_settings,
	"honeypots_config_path": "",
}

with open(os.path.join(install_dir, "config.json"), "w", encoding="utf-8") as f:
	json.dump(config, f, indent=2, sort_keys=True)
PY

	chown "$HONEYPOT_USER":"$HONEYPOT_USER" "$INSTALL_DIR/config.json"
	chmod 640 "$INSTALL_DIR/config.json"
}

setup_systemd() {
	if ! command -v systemctl >/dev/null 2>&1; then
		return 1
	fi
	if ! systemctl list-unit-files >/dev/null 2>&1; then
		return 1
	fi

	local port_mapping_dependencies=""
	if [[ "$PORT_MAPPING_MANAGED_BY_SYSTEMD" = "yes" ]]; then
		port_mapping_dependencies=$'After=honeypot-port-map.service\nRequires=honeypot-port-map.service\n'
	fi

	cat <<EOF > /etc/systemd/system/honeypot-client.service
[Unit]
Description=Honeypot client
After=network-online.target
Wants=network-online.target
${port_mapping_dependencies}StartLimitIntervalSec=300
StartLimitBurst=5

[Service]
Type=simple
User=$HONEYPOT_USER
WorkingDirectory=$INSTALL_DIR
ExecStartPre=/usr/bin/test -f $INSTALL_DIR/config.json
Environment=PYTHONUNBUFFERED=1
Environment=PYTHONNOUSERSITE=1
ExecStart=/usr/bin/python3 -s $INSTALL_DIR/honeypot_client.py
StandardOutput=append:$INSTALL_DIR/client.log
StandardError=append:$INSTALL_DIR/client.log
Restart=on-failure
RestartSec=5

# Security hardening
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=$INSTALL_DIR/logs
ReadWritePaths=$INSTALL_DIR/client.log
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
RestrictRealtime=true
RestrictSUIDSGID=true

[Install]
WantedBy=multi-user.target
EOF

	systemctl daemon-reload
	systemctl enable --now honeypot-client
}

setup_cron() {
	local cron_line="@reboot PYTHONNOUSERSITE=1 /usr/bin/python3 -s $INSTALL_DIR/honeypot_client.py >> $INSTALL_DIR/client.log 2>&1"
	(crontab -u "$HONEYPOT_USER" -l 2>/dev/null | grep -v "honeypot_client.py" || true; echo "$cron_line") | crontab -u "$HONEYPOT_USER" -
}

main() {
	require_root
	parse_args "$@"
	validate_args

	install_dependencies
	ensure_user_and_dirs
	install_python_packages
	fix_honeypots_compat
	download_client_files
	write_config

	if [[ "$MAP_PORTS" = "yes" ]]; then
		write_port_map_script
		if ! setup_port_mapping_service; then
			echo "systemd not available. Applying native-port redirects now and restoring them with cron." >&2
			setup_port_mapping_cron
		fi
	elif [[ -f "$INSTALL_DIR/port-map.sh" || -f /etc/systemd/system/honeypot-port-map.service || -f /etc/cron.d/honeypot-port-map ]]; then
		# Replace older one-way mapping scripts so a reinstallation can cleanly
		# switch this host back to backup ports.
		write_port_map_script
		disable_port_mapping
	fi

	if ! setup_systemd; then
		echo "systemd not available. Falling back to cron @reboot." >&2
		setup_cron
	fi

	echo "Honeypot client installed in $INSTALL_DIR"
	echo "Config: $INSTALL_DIR/config.json"
	if [[ "$MAP_PORTS" = "yes" ]]; then
		echo "Native-port redirects are active."
		echo "Mapping script: $INSTALL_DIR/port-map.sh"
	else
		echo "Backup ports selected. No native-port redirects were created."
		echo "Connect to the high ports in config.json."
	fi
}

main "$@"
